#!/usr/bin/env node

const rge = require("@freddieridell/regex-generator-expander");

const generator = rge({
	root: ({ preamble, number, xx, job, postamble, hashtags }) => [
		rge`${preamble} ${number} more ${xx} ${job}. ${postamble}`,
		rge`${preamble} ${number} more ${xx} ${job}. ${postamble} ${hashtags}`,
	],

	preamble: () => [
		"All top scale-ups know you need",
		"Crossing the chasm requires",
		"Have people tried putting",
		"Here's a world I'd like to see:",
		"Hey, how 'bout",
		"How much longer until we have",
		"I can't wait until there's",
		"In 2021, the world needs",
		"It's 2020! When will we get",
		"Not enough companies have",
		"Serious talk: I need to see",
		"Thought leaders are trying to get",
		"We'll never #resist @realdonaldtrump without",
		"When will @elonmusk have",
		"just had a beautiful thought...",
		"think it's about time for",
		"what's the best way to #disrupt #startups? Simple:",
	],

	number: () => [
		"10X more",
		"Unsplashed stock photos with",
		"a board room full of",
		"a few",
		"a fucking butt tonne more",
		"a handful of",
		"a slide deck of",
		"a team of",
		"enough",
		"juuuuuusst a few more",
		"lots of",
		"many many many many",
		"many many many",
		"many many",
		"many",
		"more",
		"oodles of",
		"some",
		"the",
		"tonnes of",
	],

	xx: () => [
		"broards",
		"chiquitas",
		"cutie-pies",
		"cuties",
		"dames",
		"females",
		"gals",
		"gurls",
		"honey bunnies",
		"hoochie coochie mammas",
		"laaadies",
		"ladies",
		"lovely ladies",
		"lovely lovely ladies",
		"lovely lovely lovely ladies",
		"lovely lovely lovely lovely ladies",
		"of the fairer sex",
		"senioritas",
		"skirts",
		"spicy mamma jammas",
		"strong independent women",
		"womenfolk",
	],

	job: () => [
		"advocating for vue.js",
		"banging on about angular",
		"behind keyboards",
		"being thought leaders",
		"boshing out a some serverless apps",
		"building microservices",
		"calling the shots",
		"coordinating a load of goroutines",
		"crunching numbers",
		"crunching the numbers",
		"defining schemas",
		"depricating some perl codebases",
		"doing git merges",
		"doing git pulls",
		"doing git rebases",
		"doing programming",
		"down the old code hole",
		"explaining monads to people",
		"fucking about with mercurial",
		"generating varadic types",
		"having a go at WASM",
		"making web apps",
		"managaging databases",
		"on the blockchain",
		"opening issues",
		"orchestrating kubernetes",
		"plugging in USBs",
		"programming something",
		"publishing to NPM",
		"pushing to production",
		"running open source projects",
		"running the numbers",
		"smashing out some c++",
		"taking over",
		"talking about react",
		"thinking about codes",
		"throwing errors",
		"training some neural nets",
		"using webpack",
		"watching robot wars",
		"writing bash scripts",
		"writing some ruby koans",
	],

	postamble: ({}) => [
		"@ycombinator",
		"And yet we've been saying this for years!",
		"Awooooogaa",
		"But hey, what do I know?!?",
		"But maybe that's just me, what do you think?",
		"Do I need to say it again?",
		"It is #2020 after all",
		"Lovely",
		"Retweet if you agree",
		"do you feel me?",
		"don't you think..?",
		"if not now, then when?",
		"nice",
	],

	hashtags: ({ hashtag }) => [
		rge`${hashtag}`,
		rge`${hashtag} ${hashtag}`,
		rge`${hashtag} ${hashtag} ${hashtag}`,
	],
	hashtag: () => [
		"#EveryLittleHelps",
		"#FridayIsGuyday",
		"#JustMyTake",
		"#JusticeServed",
		"#MotivationMonday",
		"#SaturdayWomenMatterToday",
		"#SundayFunday",
		"#ThoughtLeadership",
		"#ThursdayThoughts",
		"#TuesdayTutelage",
		"#WisdomWednesday",
		"#femenism",
		"#progressive",
	],
});

new Array(5).fill(null).forEach(() => {
	console.log(generator.root());
});
